AWSTemplateFormatVersion: 2010-09-09
Description: Lambda Template for GA Batch Import

Parameters:
  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:
  GaBatchImportRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Env}-ga-batch-import-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${Env}-ga-batch-import-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateExportTask
  GaBatchImportLambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          apiUrl: !If [
            IsStg,
            'https://api.stg.switch-plus.jp/api/analysis/ga-batch-import',
            'https://api.switch-plus.jp/api/analysis/ga-batch-import'
          ]
      FunctionName: !Sub ${Env}-ga-batch-import
      Handler: index.lambda_handler
      Role: !GetAtt GaBatchImportRole.Arn
      Runtime: python3.9
      Description: !Sub '[${Env}] Execute ga batch import api'
      Code:
        ZipFile: |
          import boto3
          import json
          import re
          import os
          from urllib import request, parse
          from pprint import pprint
          apiUrl = os.environ['apiUrl']

          def lambda_handler(event, context):
              req = request.Request(apiUrl)
              with request.urlopen(req) as res:
                  # resは http.client.HTTPResponse
                  body = json.loads(res.read()) # レスポンスボディ
                  headers = res.getheaders() # ヘッダー(dict)
                  status = res.getcode() # ステータスコード
                  pprint(headers)
                  pprint(status)
                  pprint(body)
  GaBatchImportLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GaBatchImportLambda}
      RetentionInDays: 14
