AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront Template for Action History

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod
  ActionHistoryWebBeaconApiUrl:
    Type: String
    Description: The shared value will be passed to this parameter by parent stack.

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:

  ##### CloudFront Distribution の作成 #####
  # ※カスタムオリジンの設定はCloudFrontでは対応していない
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html#cfn-cloudfront-distribution-distributionconfig
  ActionHistoryDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - 'cdn.stg.switch-plus.jp'
        Origins:
          - Id: ActionHistoryApiGatewayOrigin
            DomainName: !Ref ActionHistoryWebBeaconApiUrl
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        Comment: cdn distribution
        Enabled: true
        IPV6Enabled: false
        DefaultCacheBehavior:
          TargetOriginId: ActionHistoryApiGatewayOrigin
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !If [
            IsStg,
            !Sub 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/84e89707-1d47-4b58-a1e2-4bc13a214951',
            !Sub 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/2092b2b3-823f-4d48-9713-04ef3b3e0944'
          ]
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-action-history-distribution'
  DomainAssociateToActionHistoryDistribution:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !If [IsStg, 'cdn.stg.switch-plus.jp', 'cdn.switch-plus.jp']
      HostedZoneId: !If [IsStg, 'Z0733895VBADANRGGAJM', 'Z037803221ZH1F5RB8GDA']
      Type: A
      AliasTarget:
        DNSName: !GetAtt ActionHistoryDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # 固定値 @ref https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html#cfn-route53-aliastarget-hostedzoneid
