AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway Template for Action History

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod
  ActionHistory001ApiGateway2SqsRole:
    Type: String
    Description: The shared value will be passed to this parameter by parent stack.

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:
  ActionHistory001ApiGateway2SqsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: switch-plus-infra
        S3Key: resources/templates/action-history/services/lambda/001_agw2sqs/lambda_function.zip
      FunctionName: !Sub ${Env}-${ServiceName}-action-history-001-agw2sqs
      Handler: lambda_function.lambda_handler
      Role: !Ref ActionHistory001ApiGateway2SqsRole
      Runtime: python3.9
      Description: Send message to SQS from APIGateway for action history.
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${ActionHistory001ApiGateway2SqsLambda}
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  ActionHistory001ApiGateway2SqsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ActionHistory001ApiGateway2SqsLambda}
      RetentionInDays: 14

Outputs:
  ActionHistory001ApiGateway2SqsLambda:
    Value: !GetAtt ActionHistory001ApiGateway2SqsLambda.Arn
    Export:
      Name: ActionHistory001ApiGateway2SqsLambda
