AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template in App

Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t3.small
    AllowedValues:
      - db.t3.small
      - db.t3.medium

Resources:
  SSMParamServiceName:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: /SwitchPlus/Name
      Value: !Ref ServiceName

  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: stg-app-pipeline
      ArtifactStore:
        Type: S3
        Location: switch-plus-infra
      RestartExecutionOnUpdate: false
      RoleArn: # 必須
      Stages:

      ##### Sourceステージ #####
        - Name: ApiSource
          Actions:
            - Name: source-api
              Namespace: SwitchPlus # Optional
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-api
                BranchName: master
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              InputArtifacts:
                - Name: appInput
              OutputArtifacts:
                - Name: appOutput
              Region: ap-northeast-1
              RunOrder: 1

      ##### Buildステージ #####
        - Name: ApiBuild
          Actions:
            - Name: build-api
              Namespace: SwitchPlus # Optional
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-api
                BranchName: master
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              InputArtifacts:
                - Name: appInput
              OutputArtifacts:
                - Name: appOutput
              Region: ap-northeast-1
              RunOrder: 1

      ##### Deployステージ #####
        - Name: ApiDeploy
          Actions:
            - Name: deploy-api
              Namespace: SwitchPlus # Optional
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-api
                BranchName: master
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              InputArtifacts:
                - Name: appInput
              OutputArtifacts:
                - Name: appOutput
              Region: ap-northeast-1
              RunOrder: 1
      Tags:
        - Key: Name
          Value: stg-app-pipeline

Outputs:
  MyPipelineVersion:
    Value: !GetAtt MyPipeline.Version

