AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template in App

Resources:
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: stg-app-pipeline
      ArtifactStore:
        Type: S3
        Location: switch-plus-infra
      RestartExecutionOnUpdate: false
      RoleArn: arn:aws:iam::176282227532:role/CodePipelineServiceRole
      Stages:

      ##### Sourceステージ #####
        - Name: ApiSource
          Actions:
            - Name: api-source
              Region: ap-northeast-1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-api
                BranchName: feature/test_pipeline_app_repository
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              OutputArtifacts:
                - Name: apiBuildArtifact
              RunOrder: 1

      ##### Buildステージ #####
        - Name: ApiBuild
          Actions:
            - Name: api-build-image
              Region: ap-northeast-1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref ApiImageBuildProject
              InputArtifacts:
                - Name: apiBuildArtifact
              OutputArtifacts:
                - Name: apiTestArtifact
              RunOrder: 1

        - Name: ApiTest
          Actions:
            - Name: api-test
              Region: ap-northeast-1
              ActionTypeId:
                Category: Test
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref ApiTestProject
              InputArtifacts:
                - Name: apiBuildArtifact
              RunOrder: 2


  ApiImageBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      ServiceRole: arn:aws:iam::176282227532:role/CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: .buildspec.yml

  ApiTestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      ServiceRole: arn:aws:iam::176282227532:role/CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: .testspec.yml

