AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Api Pipeline Template
Resources:
  ApiPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: stg-api-pipeline
      ArtifactStore:
        Type: S3
        Location: switch-plus-infra
      RestartExecutionOnUpdate: false
      RoleArn: arn:aws:iam::176282227532:role/CodePipelineServiceRole
      Stages:

      ##### Sourceステージ #####
        - Name: ApiSource
          Actions:
            - Name: api-source
              Region: ap-northeast-1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-api
                BranchName: feature/IM-add_pipeline
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              OutputArtifacts:
                - Name: apiBuildArtifact
              RunOrder: 1

      ##### Buildステージ #####
        - Name: ApiBuild
          Actions:
            - Name: api-build-image
              Region: ap-northeast-1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref ApiImageBuildProject
              InputArtifacts:
                - Name: apiBuildArtifact
              OutputArtifacts:
                - Name: apiTestArtifact
              RunOrder: 1

  ApiImageBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Type: PARAMETER_STORE
            Name: AWS_ACCESS_KEY
            Value: /switch-plus/aws_access_key
          - Type: PARAMETER_STORE
            Name: AWS_SECRET_ACCESS_KEY
            Value: /switch-plus/aws_secret_access_key
          - Type: PARAMETER_STORE
            Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Type: PLAINTEXT
            Name: AWS_REGION
            Value: !Ref AWS::Region
          - Type: PLAINTEXT
            Name: BUCKET
            Value: switch-plus
          - Type: PLAINTEXT
            Name: ENV
            Value: stg
          - Type: PLAINTEXT
            Name: IMAGE_NAME
            Value: cw-imedia-api
      ServiceRole: arn:aws:iam::176282227532:role/CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: .buildspec.yml
