AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway Template for Action History

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

  ActionHistory001ApiGateway2SqsLambda:
    Type: String
    Description: The shared value will be passed to this parameter by parent stack.

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:
  ActionHistoryWebBeaconApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      Name: !Sub '${Env}-action-history-web-beacon'
      ProtocolType: HTTP
      Description: Web Beacon for Action History
  ActionHistoryWebBeaconApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ActionHistoryWebBeaconApiGateway
      StageName: $default
      Description: Default Stage
      AutoDeploy: true
  ActionHistoryWebBeaconApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ActionHistoryWebBeaconApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Ref ActionHistory001ApiGateway2SqsLambda
      PayloadFormatVersion: 2.0
  ActionHistoryWebBeaconApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ActionHistoryWebBeaconApiGateway
      RouteKey: 'GET /b.gif'
      Target: !Join
        - /
        - - integrations
          - !Ref ActionHistoryWebBeaconApiIntegration

Outputs:
  WebBeaconApiUrl:
    Value: !Sub
      - "${ApiId}.execute-api.${AWS::Region}.amazonaws.com"
      - ApiId: !Ref ActionHistoryWebBeaconApiGateway
    Description: ActionHistory WebBeacon API Gateway url.
