AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway Template for Action History

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:
  ActionHistorySaveDynamodbQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Env}-${ServiceName}-action-history-save-dynamodb-queue

Outputs:
  ActionHistorySaveDynamodbQueue:
    Value: !GetAtt ActionHistorySaveDynamodbQueue.Arn
    Export:
      Name: ActionHistorySaveDynamodbQueue
  ActionHistorySaveDynamodbQueueName:
    Value: !GetAtt ActionHistorySaveDynamodbQueue.QueueName
    Export:
      Name: ActionHistorySaveDynamodbQueueName
