AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront Template in Application Layer

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:

  ##### CloudFront Distribution の作成 #####
  ContentDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: content distribution
        Enabled: true
        IPV6Enabled: false
        Origins:
          - Id: S3Origin
            DomainName: stg-imedia-cms.s3.ap-northeast-1.amazonaws.com
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: true
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          FunctionAssociations: !If
            - IsStg
            # CFへのリクエスト時にBasic認証をおこなう
            - EventType:
              FunctionARN:
                Fn::GetAtt:
                  - BasicAuthCloudFrontFunction
                  - FunctionARN
            - !Ref AWS::NoValue
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
            # CloudFrontDefaultCertificate: !If [IsProd, false, true]
            # SslSupportMethod: 'sni-only'
            # AcmCertificateArn: !If [IsProd, !Sub 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/${SSLCertificateId}', '']
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-distribution'


  ##### CloudFrontからS3への OriginAccessIdentity の作成 #####
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: S3Origin


  ##### CloudFrontDistributionに対する Functionの作成 (ステージング環境のみ) #####
  BasicAuthCloudFrontFunction:
    Type: AWS::CloudFront::Function
    Conditions: IsStg
    Properties:
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var headers = request.headers;

          var authUser = '{{resolve:ssm:/switch-plus/basic_user}}';
          var authPass = '{{resolve:ssm:/switch-plus/basic_pass}}';
          var tmp = authUser + ':' + authPass;
          var authString = 'Basic ' + tmp.toString('base64');

          if (
            typeof headers.authorization === "undefined" ||
            headers.authorization.value !== authString
          ) {
            return {
              statusCode: 401,
              statusDescription: "Unauthorized",
              headers: { "www-authenticate": { value: "Basic" } }
            };
          }

          return request;
        }
      FunctionConfig:
        Comment: basic authentication to stg-s3
        Runtime: cloudfront-js-1.0
      Name: basic-authentication

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: stg-imedia-cms
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::stg-imedia-cms/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}

        #   CachePolicy:
        #     Type: AWS::CloudFront::CachePolicy
        #     Properties:
        #       CachePolicyConfig:
        #         DefaultTTL: 100
        #         MaxTTL: 31536000
        #         MinTTL: 86400
        #         Name: !Sub '${Env}-${ServiceName}-cachepolicy'
        #         ParametersInCacheKeyAndForwardedToOrigin:
        #           CookiesConfig:
        #             CookieBehavior: all
        #           EnableAcceptEncodingBrotli: false
        #           EnableAcceptEncodingGzip: false
        #           HeadersConfig:
        #             HeaderBehavior: whitelist
        #           QueryStringsConfig:
        #             QueryStringBehavior: all

