AWSTemplateFormatVersion: 2010-09-09
Description: Database Template in Application Layer

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.10.1
      EngineMode: provisioned
      DBClusterIdentifier: !Sub '${Env}-cluster'
      DBSubnetGroupName: !Ref DBSubnetGroup
      DatabaseName: switch_plus
      DeletionProtection: false
      MasterUsername: !Sub '{{resolve:ssm:/switch-plus/${Env}/db_master_username}}'
      MasterUserPassword: !Sub '{{resolve:ssm-secure:/switch-plus/${Env}/db_master_userpass}}'
      Port: 3306
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub '${Env}-SecGroupDb'
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-cluster'

  DBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Sub '${Env} aurora parameter group'
      Family: aurora-mysql5.7
      Parameters:
        time_zone: Asia/Tokyo
        character_set_client: utf8mb4
        character_set_database: utf8mb4
        character_set_results: utf8mb4
        character_set_connection: utf8mb4
        character_set_server: utf8mb4
      Tags:
        - Key: Name
          Value: !Sub '${Env}-cluster-parameter-group'

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-mysql
      DBInstanceClass: db.t2.small
      DBInstanceIdentifier: !Sub '${Env}-db'
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-db'

  DBInstance2:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Condition: IsProd
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-mysql
      DBInstanceClass: db.t2.small
      DBInstanceIdentifier: !Sub '${Env}-db-replica'
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-db-readreplica'

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub '${Env} Imedia DB Parameter Group'
      Family: aurora-mysql5.7
      Parameters:
        max_allowed_packet: 100000
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-db-parameter-group'

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${Env} Imedia DB Subnet Group'
      SubnetIds:
        - Fn::ImportValue: !Sub '${Env}-DBPrivateSubnetA'
        - Fn::ImportValue: !Sub '${Env}-DBPrivateSubnetB'
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-db-subnet-group'

