AWSTemplateFormatVersion: 2010-09-09
Description: Database Template in Application Layer

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineVersion: 5.7.mysql_aurora.2.10.1
      EngineMode: provisioned
      DBClusterIdentifier: !Sub '${Env}-cluster'
        # DBClusterParameterGroupName: aurora-mysql5.7
      DBSubnetGroupName: !Ref DBSubnetGroup
      DatabaseName: switch_plus
      DeletionProtection: false
      MasterUsername: !Sub '{{resolve:ssm-secure:/switch-plus/${Env}/master_username}}'
      MasterUserPassword: !Sub '{{resolve:ssm-secure:/switch-plus/${Env}/master_userpass}}'
      Port: 3306
      VpcSecurityGroupIds:
        - !ImportValue SecGroupDb
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-cluster'

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      Engine: aurora-mysql
      DBInstanceClass: db.t2.small
      DBInstanceIdentifier: !Sub '${Env}-db'
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-db'

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: Staging Imedia DB Parameter Group
      Family: aurora-mysql5.7
      Parameters:
        max_allowed_packet: 1024
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-db-parameter-group'

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Staging Imedia DB Subnet Group
      SubnetIds:
        - !ImportValue DBPrivateSubnetA
        - !ImportValue DBPrivateSubnetB
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-db-subnet-group'

