AWSTemplateFormatVersion: "2010-09-09"
Description: IAM User and Role, Policy in resources

Resources:
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ECSTaskExecutionRole
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Principal": {
              "Service": "ecs-tasks.amazonaws.com"
            },
            "Action": "sts:AssumeRole",
            "Effect": "Allow" 
          }
        ]
      }
      Description: ECS ServiceRole

  ECSServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ECSServicePolicy
      PolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "ecr:GetAuthorizationToken",
                      "ecr:BatchCheckLayerAvailability",
                      "ecr:GetDownloadUrlForLayer",
                      "ecr:BatchGetImage",
                      "logs:CreateLogStream",
                      "logs:PutLogEvents"
                  ],
                  "Resource": "*"
              },
              {
                  "Effect": "Allow",
                  "Action": [
                      "s3:GetObject"
                  ],
                  "Resource": [
                      "arn:aws:s3:::switch-plus/env/*"
                  ]
              },
              {
                  "Effect": "Allow",
                  "Action": [
                      "s3:GetBucketLocation"
                  ],
                  "Resource": [
                      "arn:aws:s3:::switch-plus"
                  ]
              }
          ]
      }
      Roles:
        - !Ref ECSTaskExecutionRole

  ECSServiceTaskRoleForExecAccessToECS:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ECSServiceTaskRoleForExecAccessToECS
      AssumeRolePolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Principal": {
                      "Service": "ecs-tasks.amazonaws.com"
                  },
                  "Action": "sts:AssumeRole",
                  "Effect": "Allow"
              }
          ]
      }
      Description: ECS ServiceRole

  ECSServiceTaskRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ECSServiceTaskRolePolicy
      PolicyDocument: {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "ecr:GetAuthorizationToken",
                      "ecr:BatchCheckLayerAvailability",
                      "ecr:GetDownloadUrlForLayer",
                      "ecr:BatchGetImage",
                      "cloudwatch:PutMetricData",
                      "ec2:DescribeVolumes",
                      "ec2:DescribeTags",
                      "logs:PutLogEvents",
                      "logs:DescribeLogStreams",
                      "logs:DescribeLogGroups",
                      "logs:CreateLogStream",
                      "logs:CreateLogGroup"
                  ],
                  "Resource": "*"
              },
              {
                  "Effect": "Allow",
                  "Action": [
                      "ssmmessages:CreateControlChannel",
                      "ssmmessages:CreateDataChannel",
                      "ssmmessages:OpenControlChannel",
                      "ssmmessages:OpenDataChannel"
                  ],
                  "Resource": "*"
              }
          ]
      }
      Roles:
        - !Ref ECSServiceTaskRoleForExecAccessToECS

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Principal": {
              "Service": "lambda.amazonaws.com"
            },
            "Action": "sts:AssumeRole",
            "Effect": "Allow" 
          }
        ]
      }
      Description: Lambda Execution Role

  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaBasicAuthenticationExecutionPolicy
      PolicyDocument: {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": "logs:CreateLogGroup",
            "Resource": "arn:aws:logs:ap-northeast-1:176282227532:*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ],
            "Resource": [
              "arn:aws:logs:ap-northeast-1:176282227532:log-group:/aws/lambda/Basic-Authentication:*"
            ]
          }
        ]
      }
      Roles:
        - !Ref LambdaExecutionRole

Outputs:
  ECSTaskExecutionRole:
    Value: !GetAtt ECSTaskExecutionRole.Arn
    Export:
      Name: ECSTaskExecutionRole
  ECSServiceTaskRolePolicy:
    Value: !GetAtt ECSServiceTaskRoleForExecAccessToECS.Arn
    Export:
      Name: ECSServiceTaskRoleForExecAccessToECS
  LambdaExecutionRole:
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRole

