AWSTemplateFormatVersion: 2010-09-09
Description: API Gateway Template for Action History

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:
  RedirectSetCookieRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Env}-${ServiceName}-redirect-set-cookie-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${Env}-${ServiceName}-redirect-set-cookie-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: "*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:CreateExportTask
  RedirectSetCookieLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: switch-plus-infra
        S3Key: redirect-set-cookie/templates/services/lambda/lambda_function-220129.zip
      FunctionName: !Sub ${Env}-${ServiceName}-redirect-set-cookie
      Handler: lambda_function.lambda_handler
      Role: !GetAtt RedirectSetCookieRole.Arn
      Runtime: python3.9
      Description: !Sub '[${Env}] Redirect response and set cookie.'
  RedirectSetCookieLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${RedirectSetCookieLambda}
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
  RedirectSetCookieLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${RedirectSetCookieLambda}
      RetentionInDays: 14

Outputs:
  RedirectSetCookieLambda:
    Value: !GetAtt RedirectSetCookieLambda.Arn
    Export:
      Name: RedirectSetCookieLambda
