AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Action History Template

Parameters:
  ServiceName:
    Type: String
    Default: switchplus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:
  ActionHistoryWebBeaconApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: !If [IsStg, 'a.stg.switch-plus.jp', 'a.switch-plus.jp']
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: !If [
            IsStg,
            !Sub 'arn:aws:acm:ap-northeast-1:${AWS::AccountId}:certificate/aa91ee9b-15fb-49b5-9155-52f3c3900e86',
            !Sub 'arn:aws:acm:ap-northeast-1:${AWS::AccountId}:certificate/e0a91fd8-94a0-4c4c-b6d7-a8d2713fee27'
          ]
          CertificateName: !If [IsStg, 'stg.switch-plus.jp', 'switch-plus.jp']
  ActionHistoryWebBeaconApiGateway:
    Type: AWS::ApiGatewayV2::Api
    Properties: 
      Name: !Sub '${Env}-action-history-web-beacon'
      ProtocolType: HTTP
      Description: !Sub '[${Env}] Web Beacon for Action History'
      DisableExecuteApiEndpoint: true
  ActionHistoryWebBeaconApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ActionHistoryWebBeaconApiGateway
      StageName: $default
      Description: Default Stage
      AutoDeploy: true
  ActionHistoryWebBeaconApiIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ActionHistoryWebBeaconApiGateway
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:aws:lambda:ap-northeast-1:176282227532:function:${Env}-action-history-001-agw2sqs'
      PayloadFormatVersion: 2.0
  ActionHistoryWebBeaconApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ActionHistoryWebBeaconApiGateway
      RouteKey: 'GET /b.gif'
      Target: !Join
        - /
        - - integrations
          - !Ref ActionHistoryWebBeaconApiIntegration
  ActionHistoryApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      DomainName: !If [IsStg, 'a.stg.switch-plus.jp', 'a.switch-plus.jp']
      ApiId: !Ref ActionHistoryWebBeaconApiGateway
      Stage: !Ref ActionHistoryWebBeaconApiStage
      ApiMappingKey: ''
  ActionHistory002Sqs2DynamoDBLambdaEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Sub 'arn:aws:sqs:ap-northeast-1:176282227532:${Env}-action-history-save-dynamodb-queue'
      FunctionName: !Sub 'arn:aws:lambda:ap-northeast-1:176282227532:function:${Env}-action-history-002-sqs2dynamodb'
  DomainAssociateToActionHistoryDistribution:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !If [IsStg, 'a.stg.switch-plus.jp', 'a.switch-plus.jp']
      HostedZoneId: !If [IsStg, 'Z09183552LBI6Y2LBA751', 'Z0005521QYN2C1X4165B']
      Type: A
      AliasTarget:
        DNSName: !GetAtt ActionHistoryWebBeaconApiDomainName.RegionalDomainName
        HostedZoneId: !GetAtt ActionHistoryWebBeaconApiDomainName.RegionalHostedZoneId
