AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Resources:
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./iam.yml

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./back/templates/api.yml
      Parameters:
        Env: !Ref Env

  App:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./front/templates/app.yml
      Parameters:
        Env: !Ref Env
