AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template

Parameters:
  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/pipelines/back/templates/api.yml
      Parameters:
        Env: !Ref Env

  App:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/pipelines/front/templates/app.yml
      Parameters:
        Env: !Ref Env

  Admin:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/pipelines/back/templates/admin.yml
      Parameters:
        Env: !Ref Env

