AWSTemplateFormatVersion: "2010-09-09"
Description: All Domain Certificate

Resources:
  # CloudFrontで使用するSSL証明書は リージョンがバージニア北部でなければならないため、コンソール上から作成
  # 下記CloudFront外で使用するSSL証明書
  DomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: switch-plus.jp
      DomainValidationOptions:
        - DomainName: switch-plus.jp
          HostedZoneId: Z06069631TP3ZZ0V33UKJ
      SubjectAlternativeNames:
        - '*.switch-plus.jp'
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: switch-plus
