AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template for drawing diagram

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network.yml

  Security:
    Type: AWS::CloudFormation::Stack
    DependsOn: Network
    Properties:
      TemplateURL: ./securities/security_group.yml

  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./securities/iam.yml

  Cloudfront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./applications/cloudfront.yml

  DB:
    Type: AWS::CloudFormation::Stack
    DependsOn: [Network, IAM, Security]
    Properties:
      TemplateURL: ./applications/db.yml

  ECS:
    Type: AWS::CloudFormation::Stack
    DependsOn: [Network, IAM, Security]
    Properties:
      TemplateURL: ./applications/ecs.yml


