AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template for drawing diagram

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./network.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  Security:
    Type: AWS::CloudFormation::Stack
    DependsOn: Network
    Properties:
      TemplateURL: ./securities/security_group.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  Cloudfront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./applications/cloudfront.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  DB:
    Type: AWS::CloudFormation::Stack
    DependsOn: [Network, IAM, Security]
    Properties:
      TemplateURL: ./applications/db.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  ECSCluster:
    Type: AWS::CloudFormation::Stack
    DependsOn: [Network, Security]
    Properties:
      TemplateURL: ./applications/ecs/cluster.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  ECSApi:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ECSCluster]
    Properties:
      TemplateURL: ./applications/ecs/api.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  ECSAdmin:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ECSCluster]
    Properties:
      TemplateURL: ./applications/ecs/admin.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  ECSBatch:
    Type: AWS::CloudFormation::Stack
    DependsOn: [ECSCluster]
    Properties:
      TemplateURL: ./applications/ecs/batch.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

