AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/resources/templates/network.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  Security:
    Type: AWS::CloudFormation::Stack
    DependsOn: Network
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/resources/templates/securities/security_group.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  Cloudfront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/resources/templates/applications/cloudfront.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  DB:
    Type: AWS::CloudFormation::Stack
    DependsOn: [Network, Security]
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/resources/templates/applications/db.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName

  ECS:
    Type: AWS::CloudFormation::Stack
    DependsOn: [Network, Security]
    Properties:
      TemplateURL: https://switch-plus-infra.s3.ap-northeast-1.amazonaws.com/resources/templates/applications/ecs.yml
      Parameters:
        Env: !Ref Env
        ServiceName: !Ref ServiceName


