AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront Template for Event Tracking

Parameters:
  ServiceName:
    Type: String
    Default: switch_plus
    Description: Enter service name

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsStg: !Equals [!Ref Env, 'stg']

Resources:
  ##### CloudFront Distribution の作成 #####
  # ※カスタムオリジンの設定はCloudFrontでは対応していない
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html#cfn-cloudfront-distribution-distributionconfig
  EventTrackingDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !If [IsStg, 'c.stg.switch-plus.jp', 'c.stg.switch-plus.jp']
        Origins:
          - Id: EventTrackingSESEventOrigin
            DomainName: !If [IsStg, 'r.ap-northeast-1.awstrack.me', 'r.ap-northeast-1.awstrack.me']
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
        Comment: !Sub '[${Env}] Event Tracking Distribution'
        Enabled: true
        IPV6Enabled: false
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: EventTrackingSESEventOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Headers:
              - '*'
        PriceClass: PriceClass_200
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn: !If [
            IsStg,
            !Sub 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/84e89707-1d47-4b58-a1e2-4bc13a214951',
            !Sub 'arn:aws:acm:us-east-1:${AWS::AccountId}:certificate/2092b2b3-823f-4d48-9713-04ef3b3e0944'
          ]
      Tags:
        - Key: Name
          Value: !Sub '${Env}-${ServiceName}-event-tracking-distribution'
  DomainAssociateToActionHistoryDistribution:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !If [IsStg, 'c.stg.switch-plus.jp', 'c.switch-plus.jp']
      HostedZoneId: !If [IsStg, 'Z0172048P9L6ZJKXTXK', 'Z06069631TP3ZZ0V33UKJ']
      Type: A
      AliasTarget:
        DNSName: !GetAtt EventTrackingDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # 固定値 @ref https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html#cfn-route53-aliastarget-hostedzoneid
