AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template in App

Parameters:
  ServiceName:
    Type: String
    Default: switch-plus

  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod

Resources:
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: stg-app-pipeline
      ArtifactStore:
        Type: S3
        Location: switch-plus-infra
      RestartExecutionOnUpdate: false
      RoleArn: arn:aws:iam::176282227532:role/CodePipelineServiceRole
      Stages:

      ##### Sourceステージ #####
        - Name: AppSource
          Actions:
            - Name: app-source
              Region: ap-northeast-1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-app
                BranchName: develop
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              OutputArtifacts:
                - Name: appBuildArtifact
              RunOrder: 1

      ##### Buildステージ #####
        - Name: AppBuild
          Actions:
            - Name: app-build
              Region: ap-northeast-1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref AppBuildProject
              InputArtifacts:
                - Name: appBuildArtifact
              OutputArtifacts:
                - Name: appTestArtifact
              RunOrder: 1

  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Type: PARAMETER_STORE
            Name: AWS_ACCESS_KEY
            Value: /switch-plus/aws_access_key
          - Type: PARAMETER_STORE
            Name: AWS_SECRET_ACCESS_KEY
            Value: /switch-plus/aws_secret_access_key
          - Type: PLAINTEXT
            Name: AWS_REGION
            Value: !Ref AWS::Region
          - Type: PLAINTEXT
            Name: ENV
            Value: stg
          - Type: PLAINTEXT
            Name: BUCKET
            Value: stg-imedia-cms
          - Type: PLAINTEXT
            Name: DISTRIBUTION_ID
            Value: E24AL2VU6Y9Z97
      ServiceRole: arn:aws:iam::176282227532:role/CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: .buildspec.yml

