AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Main Template in App

Parameters:
  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${Env}-app-pipeline'
      ArtifactStore:
        Type: S3
        Location: switch-plus-infra
      RestartExecutionOnUpdate: false
      RoleArn: !ImportValue CodePipelineServiceRole
      Stages:

      ##### Sourceステージ #####
        - Name: !Sub '${Env}-AppSource'
          Actions:
            - Name: !Sub '${Env}-app-source'
              Region: ap-northeast-1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-app
                BranchName: !If [IsProd, 'master', 'develop']
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              OutputArtifacts:
                - Name: !Sub '${Env}-AppBuildArtifact'
              RunOrder: 1

      ##### Buildステージ #####
        - Name: !Sub '${Env}-AppBuild'
          Actions:
            - Name: !Sub '${Env}-app-source'
              Region: !Ref AWS::Region
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref AppBuild
              InputArtifacts:
                - Name: !Sub '${Env}-AppBuildArtifact'
              RunOrder: 1

  AppBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Type: SECRETS_MANAGER
            Name: AWS_ACCESS_KEY
            Value: /switch-plus/aws_access_key
          - Type: SECRETS_MANAGER
            Name: AWS_SECRET_ACCESS_KEY
            Value: /switch-plus/aws_secret_access_key
          - Type: PLAINTEXT
            Name: AWS_REGION
            Value: !Ref AWS::Region
          - Type: PLAINTEXT
            Name: ENV
            Value: !Ref Env
          - Type: PLAINTEXT
            Name: BUCKET
            Value: !Sub '${Env}-imedia-cms'
          - Type: PLAINTEXT
            Name: DISTRIBUTION_ID
            Value: E24AL2VU6Y9Z97
      ServiceRole: !ImportValue CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: .buildspec.yml

