AWSTemplateFormatVersion: 2010-09-09
Description: SwitchPlus Admin Pipeline Template

Parameters:
  Env:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Enter stg or prod

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:
  AdminPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${Env}-admin-pipeline'
      ArtifactStore:
        Type: S3
        Location: switch-plus-infra
      RestartExecutionOnUpdate: false
      RoleArn: arn:aws:iam::176282227532:role/CodePipelineServiceRole
      Stages:

      ##### Sourceステージ #####
        - Name: AdminSource
          Actions:
            - Name: !Sub '${Env}-admin-source'
              Region: ap-northeast-1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                RepositoryName: cw-imedia-admin
                BranchName: !If [IsProd, 'test_prod', 'develop']
                PollForSourceChanges: true
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              OutputArtifacts:
                - Name: !Sub '${Env}-AdminBuildArtifact'
              RunOrder: 1

      ##### Buildステージ #####
        - Name: AdminBuild
          Actions:
            - Name: !Sub '${Env}-admin-build'
              Region: !Ref AWS::Region
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref AdminImageBuild
              InputArtifacts:
                - Name: !Sub '${Env}-AdminBuildArtifact'
              RunOrder: 1

  AdminImageBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Type: PARAMETER_STORE
            Name: AWS_ACCESS_KEY
            Value: /switch-plus/aws_access_key
          - Type: PARAMETER_STORE
            Name: AWS_SECRET_ACCESS_KEY
            Value: /switch-plus/aws_secret_access_key
          - Type: PLAINTEXT
            Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Type: PLAINTEXT
            Name: AWS_REGION
            Value: !Ref AWS::Region
          - Type: PLAINTEXT
            Name: IMAGE_NAME
            Value: !Sub '${Env}-switch-plus-admin'
      ServiceRole: arn:aws:iam::176282227532:role/CodeBuildServiceRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: .buildspec.yml
